### ISSUE TITLE
这个是失效了吗？

### ISSUE THREAD

**Issue by anony14** [viyv/jdsign#3]
我是在window上安装docker拉取镜像，开启来后127.0.0.1:17840/sign 测试有问题显示，sign error；

**Comment by viyv** [comment]
没有，正常使用

**Comment by anony14** [comment]
window可以用吗

**Comment by viyv** [comment]
> window可以用吗

你能正常拉取部署就能用

**Comment by stayforever99** [comment]
> > window可以用吗
> 
> 你能正常拉取部署就能用

大佬，为何拉取不到镜像，镜像不是这个吗fifaty/jdsign。我从dockerfile build 出来的镜像运行后，直接是拒绝访问，docker日志
![ac9d6a60c94141b12cd4ac1da6bee82](https://github.com/viyv/jdsign/assets/74627955/9e720258-2e46-43c1-89dd-43084a98d442)
